apiVersion: v1
kind: Namespace
metadata:
    name: memorycachesynthetictest
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: memorycachesynthetictest.cloud.insitehq.net
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: memorycachesynthetictest
  namespace: memorycachesynthetictest
spec:
  rules:
  - host: memorycachesynthetictest.cloud.insitehq.net
    http:
      paths:
      - backend:
          service:
            name: memorycachesynthetictest
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: memorycachesynthetictest
  namespace: memorycachesynthetictest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: memorycachesynthetictest
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tags.datadoghq.com/env: b2bcommerce-internal
    tags.datadoghq.com/service: memorycachesynthetictest
    tags.datadoghq.com/version: latest
  name: memorycachesynthetictest
  namespace: memorycachesynthetictest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: memorycachesynthetictest
      app.kubernetes.io/name: memorycachesynthetictest
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: memorycachesynthetictest
        app.kubernetes.io/name: memorycachesynthetictest
        tags.datadoghq.com/env: b2bcommerce-internal
        tags.datadoghq.com/service: memorycachesynthetictest
        tags.datadoghq.com/version: latest
    spec:
      containers:
      - name: memorycachesynthetictest
        image: registry.cloud.insitehq.net/memorycachesynthetictest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: CACHEMEMORYLIMITMEGABYTES
          value: "2048"
        - name: PHYSICALMEMORYLIMITPERCENTAGE
          value: "0"
        - name: DD_AGENT_HOST
          value: "datadog-windows-dev.datadog-dev.svc.cluster.local"
          # valueFrom:
          #   fieldRef:
          #     apiVersion: v1
          #     fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_PORT
          value: "8136"
        - name: DD_DOGSTATSD_HOST
          value: "datadog-windows-dev.datadog-dev.svc.cluster.local"
        - name: DD_DOGSTATSD_PORT
          value: "8135"
        - name: DD_ENV
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_APPSEC_ENABLED
          value: "true"
        - name: DD_RUNTIME_METRICS_ENABLED
          value: "true"
        - name: DD_PROFILING_ENABLED
          value: "1"
        - name: COR_ENABLE_PROFILING
          value: "1"
        - name: COR_PROFILER
          value: "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}"
        resources:
          requests:
            cpu: 1
            memory: 4096Mi
          # limits:
          #   memory: 4096Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 30
          periodSeconds: 60
          failureThreshold: 10
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        kubernetes.io/os: windows
---
apiVersion: v1
data:
  .dockerconfigjson: ewogICAiYXV0aHMiOnsKICAgICAgInJlZ2lzdHJ5LmNsb3VkLmluc2l0ZWhxLm5ldCI6ewogICAgICAgICAidXNlcm5hbWUiOiJ1cGxvYWQiLAogICAgICAgICAicGFzc3dvcmQiOiJ3VjBsQHhob255M3lzekJaIiwKICAgICAgICAgImF1dGgiOiJkWEJzYjJGa09uZFdNR3hBZUdodmJua3plWE42UWxvPSIKICAgICAgfSwKICAgICAgIm9wdGltaXplbHliMmJlbmdpbmVlcmluZy5henVyZWNyLmlvIjp7CiAgICAgICAgICJ1c2VybmFtZSI6InJlcG9zaXRvcmllcy1wdXNoIiwKICAgICAgICAgInBhc3N3b3JkIjoiRm5CYjl6WkJiOGxTV0tNUjN4TTk9Um9nRE1BVC8rdkgiLAogICAgICAgICAiYXV0aCI6ImNtVndiM05wZEc5eWFXVnpMWEIxYzJnNlJtNUNZamw2V2tKaU9HeFRWMHROVWpONFRUazlVbTluUkUxQlZDOHJka2c9IgogICAgICB9LAogICAgICAib3B0aW1pemVseWIyYnB1YmxpYy5henVyZWNyLmlvIjp7CiAgICAgICAgICJ1c2VybmFtZSI6InJlcG9zaXRvcmllcy1wdXNoIiwKICAgICAgICAgInBhc3N3b3JkIjoiUmZEUE1xenFaUWRzPUVQeHdFb2g3Y1dOUEJFVTVZc2wiLAogICAgICAgICAiYXV0aCI6ImNtVndiM05wZEc5eWFXVnpMWEIxYzJnNlVtWkVVRTF4ZW5GYVVXUnpQVVZRZUhkRmIyZzNZMWRPVUVKRlZUVlpjMnc9IgogICAgICB9CiAgIH0KfQ==
kind: Secret
metadata:
  name: regcred
  namespace: memorycachesynthetictest
type: kubernetes.io/dockerconfigjson
